// aiService.js
// Handles communication with local Ollama and Fallback logic

const OLLAMA_URL = 'http://localhost:11434/api/generate';
const OLLAMA_MODEL = 'mistral'; // or 'llama3'

const generateAiAnalysis = async (studentData) => {
  const prompt = `You are a smart academic assistant for a college student.

Here is the student's data:

Timetable:
${JSON.stringify(studentData.timetable, null, 2)}

Attendance:
${JSON.stringify(studentData.attendance, null, 2)}

Deadlines:
${JSON.stringify(studentData.deadlines, null, 2)}

Fees:
${JSON.stringify(studentData.fees, null, 2)}

Tasks:
1. Identify important issues (deadlines, low attendance, fees)
2. Detect urgency
3. Analyze available free time from timetable
4. Generate important notifications
5. Provide a short actionable suggestion

Return ONLY JSON in this format and nothing else (do not include markdown block ticks):
{
  "notifications": [
    {
      "type": "deadline | attendance | fee",
      "message": "text",
      "priority": "low | medium | high"
    }
  ],
  "insight": "short helpful suggestion"
}`;

  try {
    const response = await fetch(OLLAMA_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: OLLAMA_MODEL,
        prompt: prompt,
        stream: false,
        format: 'json'
      })
    });

    if (!response.ok) {
      throw new Error('Ollama not reachable or failed');
    }

    const data = await response.json();
    let result = null;
    
    // Parse the actual text response generated by Ollama
    try {
        // Sometimes Ollama adds backticks even with format json
        let cleanResponse = data.response.replace(/```json/g, '').replace(/```/g, '').trim();
        result = JSON.parse(cleanResponse);
    } catch (parseError) {
        throw new Error('Ollama returned invalid JSON. Falling back.');
    }
    
    return result;

  } catch (error) {
    console.log('AI Failed, using Fallback System. Error:', error.message);
    return getFallbackAnalysis(studentData);
  }
};

const getFallbackAnalysis = (data) => {
  const notifications = [];

  // Fallback: Attendance
  if (data.attendance) {
    data.attendance.forEach(att => {
      if (att.percentage < 75) {
        notifications.push({
          type: 'attendance',
          message: `Warning: Low attendance in ${att.subject} (${att.percentage}%)`,
          priority: 'high'
        });
      }
    });
  }

  // Fallback: Deadlines
  const now = new Date();
  if (data.deadlines) {
    data.deadlines.forEach(dl => {
       if (dl.status !== 'Pending') return;
       const dueDate = new Date(dl.dueDate);
       const diffDays = Math.ceil((dueDate - now)/(1000 * 60 * 60 * 24));
       if(diffDays <= 2){
           notifications.push({
              type: 'deadline',
              message: `'${dl.assignment}' is due soon!`,
              priority: 'high'
           });
       }
    });
  }

  // Fallback: Fees
  if (data.fees && data.fees.status === 'Pending') {
      notifications.push({
          type: 'fee',
          message: `Pending fees of INR ${data.fees.due} due by ${data.fees.dueDate}`,
          priority: 'medium'
      });
  }

  return {
    notifications,
    insight: "Fallback Insight: It seems Ollama is disconnected. Regardless, keep a close eye on your urgent assignments and low attendance subjects!"
  };
};

module.exports = {
  generateAiAnalysis
};
